### ISSUE TITLE
The extension is freeze after wake up from sleep

### ISSUE THREAD

**Issue by ForteDexe** [Ory0n/Resource_Monitor#101]
**Describe the bug**
The extension freezes after waking up from sleep (suspend). My PC and laptop have the same issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/73e10910-41b3-4f95-89ca-d34f0026711d)

**Desktop (please complete the following information):**
 - PC: Ubuntu 24.10, Nvidia GPU, Wayland
 - Latop: Ubuntu 24 LTS, IGPU, Wayland

**Note**
_Let me know if you need something for debugging.

**Comment by Ruuza** [comment]
Same issue. The error says: `TypeError: this.themeContext is undefined`

**Comment by gustitammam** [comment]
Happened on Fedora 41 too.

**Comment by imchivaa** [comment]
Same here,

Fedora 41 (Wayland)
GNOME 47

![image](https://github.com/user-attachments/assets/949f9478-4d8b-4882-a7e0-e23d6c17b44a)

**Comment by masoudamri** [comment]
Same error: "TypeError: this.themeContext is undefined"
running ubuntu/gnome shell 46

**Comment by marcosrochasb** [comment]
Same here.
* PC: Ubuntu 24.04, Nvidia 4060 GPU, Wayland
* Intel NUC: Ubuntu 24.04, Intel® UHD Graphics 605 (GLK 3), Wayland

Both ubuntu/gnome shell 48

**Comment by gsoul** [comment]
+1 on Ubuntu 24.04

**Comment by 0ry0n** [comment]
Please look at this #97

**Comment by olaulau** [comment]
when will it be released on gnome extensions ?

**Comment by ForteDexe** [comment]
> when will it be released on gnome extensions ?

Just download v25 from release, replace it to content in ~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n

**Comment by olaulau** [comment]
> > when will it be released on gnome extensions ?
> 
> Just download v25 from release, replace it to content in ~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n

I know, but this doesn't answer the question : when will it be released ?

**Comment by ForteDexe** [comment]
> > > when will it be released on gnome extensions ?
> > 
> > 
> > Just download v25 from release, replace it to content in ~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n
> 
> I know, but this doesn't answer the question : when will it be released ?

When he feel it ?

**Comment by 0ry0n** [comment]
The new version is now available on GNOME extensions.
