### ISSUE TITLE
this.themeContext is undefined

### ISSUE THREAD

**Issue by angousana** [Ory0n/Resource_Monitor#103]
**Describe the bug**
extension crashes

**Screenshots**
![Screenshot from 2024-11-08 20-07-32](https://github.com/user-attachments/assets/ec28d675-e9bc-434e-816e-c35d59f420cb)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 23.10

**Additional context**
it didn't happen before i updated the extension.

**Comment by 0ry0n** [comment]
Please look at this #97
