### ISSUE TITLE
Allow changing of location on taskbar to left side

### ISSUE THREAD

**Issue by ChiefGyk3D** [Ory0n/Resource_Monitor#33]
**Is your feature request related to a problem? Please describe.**
Yes the right side of the taskbar is the default place for icons and such, it gets cluttered way too easily and the left side is usually left open more.

**Describe the solution you'd like**
Allow users to switch the position of the entire taskbar from left, center, or right.

Seems really straightforward to me

**Comment by 0ry0n** [comment]
Fixed in release 16
