### ISSUE TITLE
RAM Usage indicator

### ISSUE THREAD

**Issue by palexdev** [Ory0n/Resource_Monitor#38]
Is it possible to have an option to choose between percentage and text for ram usage?
I mean, I don't really care about the percentage, I don't know how much RAM 24% is exactly for example

I think it would be more useful to express it as MB/GB used

**Comment by 0ry0n** [comment]
Thanks for collaboration. I added it in the new version. b3166e9e24f5dc7fe76ce489401d17712947c56c

**Comment by palexdev** [comment]
Thank you very much!
