### ISSUE TITLE
Gnome 42

### ISSUE THREAD

**Issue by pawelwaniek95** [Ory0n/Resource_Monitor#39]
Can we get support for Gnome 42?
I am running Gnome 42, and the extension is “outdated”

**Comment by guoqiyi** [comment]
just add "42" after "41" line to metadata.json file to make it works again, seems no bug yet

**Comment by nathanael-h** [comment]
I did this, but the settings panel do not open. I run ubuntu 22.04, and use Firefox with gnome-extension. 

I have this error in logs, I do not know if it helps one of you to adapt to version 42: 
```
Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _promisify/proto[asyncFunc]@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:420:16
  openExtensionPrefs@resource:///org/gnome/shell/ui/extensionSystem.js:240:26
  openPrefs@resource:///org/gnome/shell/misc/extensionUtils.js:227:26
  _openSystemMonitor@/home/nathanael.h/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/extension.js:456:40
```

**Comment by 0ry0n** [comment]
Thanks for collaboration. I have updated the version in the new release. b3166e9e24f5dc7fe76ce489401d17712947c56c
