### ISSUE TITLE
"Hide zero values" is enabled but a non-existent fan with 0 RPM is displayed and contributes to average.

### ISSUE THREAD

**Issue by lpinner** [Ory0n/Resource_Monitor#42]
**Describe the bug**
"Hide zero values" is enabled but a non-existent fan with 0 RPM is displayed and contributes to average.

This motherboard has never had a 2nd case fan plugged in to the 2nd case fan header, just the cpu cooler fan and a single case fan. 

**To Reproduce**

- Enable "Hide zero values".

- Either unplug a fan, or do not install one in the first place.

**Expected behavior**
When "Hide zero values" is enabled only fans with >0 RPM should be displayed and contribute to the average.

**Screenshots**
![image](https://user-images.githubusercontent.com/4827816/170226115-c5222a8b-1081-4a2c-a7b5-31b16883e4eb.png)

![image](https://user-images.githubusercontent.com/4827816/170226218-773bc893-4ec3-494b-acb2-82278cf0bc33.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version:  22.04

**Comment by 0ry0n** [comment]
That's not my extension!
