### ISSUE TITLE
auto-hide sections with zero values

### ISSUE THREAD

**Issue by ghost** [Ory0n/Resource_Monitor#44]
**Is your feature request related to a problem? Please describe.**
Nop. It's a pure aesthetic.

**Describe the solution you'd like**
Auto-hide sections with zero values.
![Screenshot from 2022-07-07 21-13-35 png-mh](https://user-images.githubusercontent.com/83843264/177816054-179ab40d-5d40-418d-b678-e37f8481aa3f.png)

**Comment by 0ry0n** [comment]
ok, it could be valid for "swap" but as far as disks are concerned it doesn't make sense as the value 0 is temporary. I will evaluate better and maybe add it in the next version. thanks.

**Comment by ghost** [comment]
Oh tqvm. But what I inferred is to dynamically hide those zero state columns. In the sense, they'll reappear when a non zero value kicks in...
