### ISSUE TITLE
[Request] Scrolling text

### ISSUE THREAD

**Issue by egarcia1360** [Ory0n/Resource_Monitor#55]
All the useful information shown by this extension unfortunately takes up quite a bit of space on the top panel and often gets cut off. If possible, it would be great to have an option whereby the text could scroll side to side, allowing for more data to be shown without getting cut off and replaced by ellipses—like so:
![image](https://i.makeagif.com/media/6-12-2015/CXpkGB.gif)

**Comment by 0ry0n** [comment]
I'm sorry, but creating the scrolling text doesn't seem feasible. I am sorry.
