### ISSUE TITLE
[Request] Add the ability to decide the order in which items are displayed

### ISSUE THREAD

**Issue by rr1231234** [Ory0n/Resource_Monitor#56]
Is it in prefs.ui?
![Screenshot from 2022-10-25 03-53-31](https://user-images.githubusercontent.com/92568853/197627281-b7ed4c10-0992-4144-9012-7e30d289c7fd.png)

**Comment by 0ry0n** [comment]
For now it is not possible to decide the display order, but I plan to add it. Maybe in the next version

**Comment by rr1231234** [comment]
Perfecto!
