### ISSUE TITLE
Custom name for Disk and GPU

### ISSUE THREAD

**Issue by alexisLefebvre** [Ory0n/Resource_Monitor#58]
**Is your feature request related to a problem? Please describe.**
The name of my GPU uses space:

> ![image](https://user-images.githubusercontent.com/2071331/201682068-27d36585-3346-4d6a-9496-a3620f560deb.png)

**Describe the solution you'd like**
Add an option to hide the name of the GPU so that I can see only usage and temperature.

Or remove the name of the GPU completely, like we don't see the name of the CPU. Or even go further and display the data about GPU in the same way than for the CPU.

**Describe alternatives you've considered**

Comment `this.add(this._elementsName[uuid]);` in `~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/extension.js`.

**Additional context**
- plugin version 18
- Ubuntu 22.04.1 LTS
- GNOME Shell 42.5

Thanks for this amazing extension!

**Comment by mrmbernardi** [comment]
![image](https://user-images.githubusercontent.com/7877312/209361762-6f2c15dd-d834-4d68-8182-3c26e5c3fc37.png)

I've got it even worse. 

One solution I was thinking of would be to have the name field in the Devices table on the GPU table be editable. This would allow you to change the name to just RTX 3070 or whatever if you wanted.

I thought this would just be as simple as setting a boolean when creating the GTK control, but I couldn't get it to work.

**Comment by GuilhermeGreggio** [comment]
![image](https://user-images.githubusercontent.com/104743143/225032401-0c5e381f-77c2-4a7f-84c2-044847165a9e.png)

Disk name need that too.
I think it would be nice if could edit the labels or just hide if it's easier to programing that way.

**Comment by smbell1979** [comment]
Just wanted to second this suggestion. Being able to hide or edit the names of the devices, mainly the GPU since it's so long would make this extension even more amazing! 

It's one of the only ones with a simple easy to read nvidia GPU monitor, so I'd love to keep using it.

**Comment by alexisLefebvre** [comment]
We can now hide the name of the GPU since 73eed8bde2538a981ab4754a9c7cd8aa15f56a7a. Thanks!
