### ISSUE TITLE
AMD GPU Thermal metrics are miscategorized under CPU

### ISSUE THREAD

**Issue by tcpkump** [Ory0n/Resource_Monitor#61]
**Describe the bug**
When trying to monitor my thermal stats on a new AMD RTX 6750XT, the devices are listed under the CPU section instead of GPU, preventing me from using the setting.

**To Reproduce**
1. Go to Settings
2. Click on Thermal
3. Scroll down to GPU Temperature > Devices
4. See that it is blank, and that "amdgpu" devices are listed inder CPU Temperature > Devices

**Expected behavior**
amdgpu devices should be listed under GPU Devices

**Screenshots**
![image](https://user-images.githubusercontent.com/20349484/206268782-4b64e382-8677-4d36-8301-5c685e6f4fe6.png)

**Desktop (please complete the following information):**
 - OS: Pop! OS (Wayland)
 - Version: 22.04

**Additional Information**
I would like to note that this feature worked perfectly with my previous GPU, an Nvidia GTX 1080 ti.

**Comment by 0ry0n** [comment]
The basic problem is that for now AMD GPU are not supported by the extension. Even fixing this problem, the problem of resource usage would remain.
However this could be a starting point for the integration of AMD GPU, but also for monitoring the temperatures of other devices that I notice in your list such as the nvme and probably the wifi card.

**Comment by 0ry0n** [comment]
Categorization fixed. The next step is to support AMD GPU. #66
