### ISSUE TITLE
RAM not showing info

### ISSUE THREAD

**Issue by eastsidelbc** [Ory0n/Resource_Monitor#62]
**Describe the bug**
Ram doesn't show 

**To Reproduce**
Just have it normally installed

**Expected behavior**
Showing RAM percentage used

**Screenshots**
![Screenshot from 2023-01-07 05-34-54](https://user-images.githubusercontent.com/101154332/211148569-ef5013ec-61a4-4196-892d-dc880588aacc.png)

**Desktop (please complete the following information):**
 - OS: Pop 22_04
 - Gnome 42.5

**Comment by 0ry0n** [comment]
I think you just need to increase the width.
Open prefs and increase it.
