### ISSUE TITLE
Alternative Icons

### ISSUE THREAD

**Issue by chrismelnyck** [Ory0n/Resource_Monitor#64]
Guys, I made alternative icons, looks good on my Ubuntu, if you like it too, you can include them in the extension. I drew them, you can share them however you want.

[icons.zip](https://github.com/0ry0n/Resource_Monitor/files/10513006/icons.zip)

**Comment by 0ry0n** [comment]
Your icons are nice, but not in line with the gnome style. I'm sorry but I won't use them. Thank you.
