### ISSUE TITLE
Disk activity is not displayed for ZFS storage pool 

### ISSUE THREAD

**Issue by Davem734** [Ory0n/Resource_Monitor#65]
**Describe the bug**
Disk activity is not displayed for a ZFS storage pool (two drives, mirrored) mounted at /RAID

**To Reproduce**
Mount ZFS storage pool at mountpoint /RAID
In settings check Stats and Space boxs for /RAID
        Space - ON
        Width=40
        Unit = Num/Gig
        Mon = Free   
        Devices 
          /home - Stats, Space
          /RAID - Stats, Space     

**Expected behavior**
Space is displayed but activity is not for the /RAID mountpoint
The /home  mountpoint is working correctly 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: 18

**Additional context**

**Comment by Davem734** [comment]
Additional info:

$ zfs --version
zfs-2.1.5-1ubuntu6~22.04.1
zfs-kmod-2.1.5-1ubuntu6

A command to get the zpool status is: 
$ zpool iostat
which returns:
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
ZFSM01      1.50T  9.40T      0     36    195  22.8M

**Comment by Davem734** [comment]
Additional info:
```
$ zfs --version
zfs-2.1.5-1ubuntu6~22.04.1
zfs-kmod-2.1.5-1ubuntu6
```
A command to get the zpool status is: 

```
$ zpool iostat
which returns:
              capacity     operations     bandwidth 
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
ZFSM01      1.50T  9.40T      0     36    195  22.8M

```

**Comment by 0ry0n** [comment]
I added a functionality in the prefs of the disk that shows all monitoring devices (/dev/*).

In the case of a ZFS pool, it is possible to monitor the statistics of the devices used for the pool (example /dev/sdb /dev/sdc) and the pool space (example /RAID).

Unfortunately for now the two things are separated. I will try to improve it in the next versions.
