### ISSUE TITLE
how to user 'Customer program'

### ISSUE THREAD

**Issue by maosocial** [Ory0n/Resource_Monitor#70]
**Describe the bug**
1. I set the Customer program to `alacritty -e htop` or `/usr/bin/alacritty -e htop`.
left-click, it says: Execution of "alacritty -e htop" failed. Command not found.

2. set it to `htop`, left-click, nothing happened.

**Comment by 0ry0n** [comment]
The command to use is the same as the one used in the terminal, es htop.

I noticed that there is a bug, if the custom-program text box has already written the program (e.g. htop) and you make the change with another option (e.g. Launch GNOME Usage), when you return to custom-program option, the written program is not used (e.g. htop) but the custom-program string is used.

This may be why you couldn’t run htop.

However reading the log files (/var/log/syslog) you should get a line similar to this
`Jul 12 14:23:57 Computer gnome-shell[xx]: error: Execution of "custom-program" failed:: Command not found`
