### ISSUE TITLE
no nvidia card but still run nvidia-smi cause error

### ISSUE THREAD

**Issue by guoqiyi** [Ory0n/Resource_Monitor#71]
**Describe the bug**
Only use intel gpu so  no install nvidia-utils,but everytime right click to open setting panel it will try to run nvidia-smi cause system errrors,it should be an option  not

**Comment by guoqiyi** [comment]
![image](https://github.com/0ry0n/Resource_Monitor/assets/3457554/8b67acfb-c22a-4b55-89df-40bacdc363ef)

**Comment by 0ry0n** [comment]
Thanks to your input, I have corrected the errors highlighted in yellow in the image. The "nvidia-smi not found" error is not an issue. For now, I intend to leave it as it could be useful for troubleshooting on NVIDIA systems.
