### ISSUE TITLE
CPU temperature error 

### ISSUE THREAD

**Issue by bahtioraliev** [Ory0n/Resource_Monitor#74]
**Describe the bug**
The CPU temp appears in “Temperature error”

**To Reproduce**
1. Restart the PC
3. The issue will appear
5. To resolve it, I just restart the temp, by toggling the feature on/off.

**Expected behavior**
The temp should appear as it does around 2 weeks ago.

**Screenshots**
I will upload it asap 

**Desktop (please complete the following information):**
 - OS: PopOS
 - Version 22.04 LTS

**Comment by DD1TTY** [comment]
I have had this issue with this extension for more than a year running Pop_OS! 22.04 installed on a Razer blade

**Comment by olaulau** [comment]
right clicking on the widget, which show the settings, makes the temperature working for me.
but each reboot I have this error again ...
