### ISSUE TITLE
RFE: Add ability to hide extensions icon.

### ISSUE THREAD

**Issue by kathenas** [Ory0n/Resource_Monitor#76]
Add ability to hide extensions icon.

For users that wish to save bar real estate, it would be a beneficial option to allow the user to hide the extension own icon. If feature could be added it would be appreciated.

**Comment by 0ry0n** [comment]
If you open the prefs panel, you can turn off the icons.
![main](https://github.com/0ry0n/Resource_Monitor/assets/45901006/7b59daf4-bb51-485d-a34b-4ee265d135af)
