### ISSUE TITLE
Add support for Gnome 45

### ISSUE THREAD

**Issue by Abdullah-2003** [Ory0n/Resource_Monitor#77]
The extension needs to be updated to work with gnome v45

**Comment by ShivamJoker** [comment]
@0ry0n any way for me to help? I am not sure how the extensions work.
But I have decent knowledge of JS, if you could point me to right direction I might send a PR.

**Comment by ksimuk** [comment]
@ShivamJoker https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by derkrasseleo** [comment]
I wish I could help, would be nice to have this extension back..

**Comment by peter-lyons-kehl** [comment]
Thank you @Sierra410 and @Braavy for #78.

Thank you @0ry0n for Resource_Monitor, and looking forward to it in GNOME 45.

**Comment by 0ry0n** [comment]
In the coming weeks a version will be released that supports gnome 45, but if you don’t wait, you can already use the version of the develop branch. :rocket: :heart:

**Comment by smbell1979** [comment]
Dev branch is working great on 45. Thank you.

**Comment by fedkad** [comment]
Still waiting for the Gnome 45 release...

**Comment by 0ry0n** [comment]
I'm waiting for approval from GNOME

**Comment by 0ry0n** [comment]
The new version is here! Thanks to everyone :heart:
