### ISSUE TITLE
No GPU info

### ISSUE THREAD

**Issue by peter-lyons-kehl** [Ory0n/Resource_Monitor#79]
No GPU info shown. Do I need to install/enable anything, or is that only for specific hardware, or for specific Linux distributions? (CPU Temperature does show up. And: Thank you.)

- Current Manjaro x86_64 `Linux spectre 6.6.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC`. 
- Hewlett-Packard HP Spectre Pro x360 G1, Intel i7
- Graphics: in-built Intel® HD Graphics 5500 (BDW GT2)
- GNOME: 44.5, X11

I do have GPU enabled. There is no bubble/space reserved for it in the top bar (as is for CPU usage). No errors at https://extensions.gnome.org/local for Resource Monitor.
![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/b5d7daff-303f-45f3-96b4-da28e879c69e)

**Comment by 0ry0n** [comment]
For now only nvidia GPUs are supported. Stay tuned for new updates.
