### ISSUE TITLE
Incorrect frequency reporting for Intel 12th gen CPUs

### ISSUE THREAD

**Issue by xtenduke** [Ory0n/Resource_Monitor#82]
Current source of CPU frequency `/sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq` is unsuitable for modern CPUs, specifically heterogeneous CPUs like Intels 12th gen. 

Attached example shows an i7 12800h running at idle.

![Screenshot from 2024-01-25 09-55-22](https://github.com/0ry0n/Resource_Monitor/assets/5002212/293773f3-7a00-4db8-aba1-7240b4ab6f16)
I think it would be better if we changed this to the highest clock speed reported across all cores.
Cores with the MAXMHZ of 3700 are E-cores and have a lower turbo clock sped.

![Screenshot from 2024-01-25 10-08-41](https://github.com/0ry0n/Resource_Monitor/assets/5002212/9d1abddf-ac4f-4301-81df-084471c9e095)

https://github.com/0ry0n/Resource_Monitor/blob/7e6b378a53f2b4eff1f479f0875185fe1eb73e96/Resource_Monitor%40Ory0n/extension.js#L2541

**Comment by 0ry0n** [comment]
Now the frequency of each core is monitored and the highest value is taken.
