### ISSUE TITLE
Add support for Gnome 46 please

### ISSUE THREAD

**Issue by Czy014** [Ory0n/Resource_Monitor#84]
Could you please update this extension to adapt it to gnome 46? I really like this extension. @0ry0n

**Comment by DanielusG** [comment]
I created a pull request to apply the extension porting, waiting for it to be approved you can use the extension from my repository, the fix is very simple, it was a matter of renaming some functions

**Comment by Czy014** [comment]
> I created a pull request to apply the extension porting, waiting for it to be approved you can use the extension from my repository, the fix is very simple, it was a matter of renaming some functions

I just pulled the code from your repo. After restarting the computer, I found that it was indeed working normally. Thank you very much for your help! @DanielusG

**Comment by DanielusG** [comment]
Glad to have been able to make a small contribution to the community :)

**Comment by ForteDexe** [comment]
It worked, thanks @DanielusG

**Comment by DanielusG** [comment]
@ForteDexe I'm sorry, I wish more people could benefit from my edit, but the repository author is probably busy and isn't merging this pull request :(

Glad to help you

**Comment by peter-lyons-kehl** [comment]
Thank you @DanielusG for the PR, and Giuseppe @0ry0n for accepting it. Has this been updated/uploaded at https://extensions.gnome.org/extension/1634/resource-monitor/ yet?

Unfortunately, for GNOME 46:
- If it were updated at extensions.gnome.org, then know: The current version from extensions.gnome.org is `21` and it doesn't work in GNOME 46 on current Manjaro x64 (last night's big update).
- I've manually re-installed from the current `master` (7e6b378a53f2b4eff1f479f0875185fe1eb73e96), which has tag `21`. Still an error (in GNOME 46, Manjaro).
- Unfortunately, contrary to the past behavior of GNOME extensions, I don't see a way to get error details. There's no such popup/expand at https://extensions.gnome.org/local/, nor in (the green) "Extensions" application.
![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/05168ac4-f1a6-49f4-b4e2-acce804241c8)

The only error message I get is in (the blue) "Extensions Manager" application: "Monitor the use of system resources like cpu, ram, disk, network and display them in gnome shell top bar."
![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/4497ad99-200d-4dbf-9a90-d7fefcbe2957)

Please investigate, and/or advise on files/commands I can run to help test/narrow this down.
![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/a19444bd-d8b0-4a3e-98af-7c11d339d492)

**Comment by DanielusG** [comment]
> Thank you @DanielusG for the PR, and Giuseppe @0ry0n for accepting it. Has this been updated/uploaded at https://extensions.gnome.org/extension/1634/resource-monitor/ yet?
> 
> Unfortunately, for GNOME 46:
> - If it were updated at extensions.gnome.org, then know: The current version from extensions.gnome.org is `21` and it doesn't work in GNOME 46 on current Manjaro x64 (last night's big update).
> - I've manually re-installed from the current `master` (7e6b378a53f2b4eff1f479f0875185fe1eb73e96), which has tag `21`. Still an error (in GNOME 46, Manjaro).
> - Unfortunately, contrary to the past behavior of GNOME extensions, I don't see a way to get error details. There's no such popup/expand at https://extensions.gnome.org/local/, nor in (the green) "Extensions" application.
> ![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/05168ac4-f1a6-49f4-b4e2-acce804241c8)
> 
> The only error message I get is in (the blue) "Extensions Manager" application: "Monitor the use of system resources like cpu, ram, disk, network and display them in gnome shell top bar."
> ![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/4497ad99-200d-4dbf-9a90-d7fefcbe2957)
> 
> Please investigate, and/or advise on files/commands I can run to help test/narrow this down.
> ![image](https://github.com/0ry0n/Resource_Monitor/assets/4270240/a19444bd-d8b0-4a3e-98af-7c11d339d492)
> 

Hi! In the photo of the error, I can see "this.add" which is the change I made in this PR, I guess the APIs changed again..
 Now in Italy it is night so tomorrow I will check it :)

**Comment by DanielusG** [comment]
@peter-kehl Hi, I took a look at your error and the error you are encountering is because of the API update of a component that Gnome 46 relies on, I solved this problem with the pull request #85.
However, it seems that in the gnome portal has not been updated yet and I don't know how to update and if it is something that only the repository owner can do.

What you can do right now, and what will surely work, is to manually install it from the develop branch of this repo at the tag
 https://github.com/0ry0n/Resource_Monitor/commit/576816b8c056070bb7bac013bab5f9e03d42667f

This is because the repository author explicitly asked for pull requests in the develop branch, so my merge and most recent changes are located there

I hope I was helpful, if you have any other questions please ask :)

**Comment by peter-lyons-kehl** [comment]
Thank you @DanielusG, the develop branch does work in GNOME 46 on current Manjaro x64.

For anyone who doesn't use GIT with remote branches much:
```bash
# if you have Resource_Monitor installed already, remove it:
rm -rf ~/.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n

git clone https://github.com/0ry0n/Resource_Monitor
cd Resource_Monitor
git pull origin develop
git checkout develop
cp -r Resource_Monitor@Ory0n ~/.local/share/gnome-shell/extensions
```

Then re-login to GNOME, or (maybe) restart "GNOME shell": Alt+F2 -> then press `r`.

**Comment by 0ry0n** [comment]
Sorry for the wait, but I am really busy. Thank you for your cooperation. @DanielusG
