### ISSUE TITLE
Left aligned issue

### ISSUE THREAD

**Issue by daogu80** [Ory0n/Resource_Monitor#88]
When the application is minimized, it will not automatically align to the left and cannot display CPU temperature
![Snipaste_2024-07-09_11-07-18](https://github.com/0ry0n/Resource_Monitor/assets/96433349/def729e1-5281-48e6-9d0a-f7118e554c96)

**Comment by 0ry0n** [comment]
The extension appears to be correctly aligned to the left. The temperature is likely not being displayed because no devices have been selected. Open the preferences and check.
