### ISSUE TITLE
GPU no info displayed

### ISSUE THREAD

**Issue by nonnt66v2** [Ory0n/Resource_Monitor#94]
![image](https://github.com/user-attachments/assets/0f83f166-ea72-40f9-923c-21eae3610ee8)
only one thing works at a time, for example if I select them all, it shows me the temperature, if I select only the 2 in the GPU section it shows me the percentage of use, if I select only the used memory it shows me only in KB not allowing me to change units of measurement

**Comment by 0ry0n** [comment]
Fixed, it was due to copy and paste :sweat_smile:
Use the develop branch version or wait for the new release, thanks.

**Comment by nonnt66v2** [comment]
_**Bella pe te Peppe**_
