### ISSUE TITLE
Gnome 46, themeContext is undefined

### ISSUE THREAD

**Issue by kron4eg** [Ory0n/Resource_Monitor#97]
**Describe the bug**
On a PREVIOUS Gnome (46) version, after recent [Release 24](https://github.com/0ry0n/Resource_Monitor/releases/tag/24) upgrade I got this message (as show in the screenshot) in the extension manager.

**To Reproduce**
1. Have Gnome 46
2. Install latest 24 release
3. Open Gnome extension manager

**Expected behavior**
No error? IDK :man_shrugging: 

**Screenshots**
![image](https://github.com/user-attachments/assets/3b64c3af-a0f5-4d34-aa38-020d74a000f7)

**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Gnome version: 46
 - Version: 24

**Comment by 0ry0n** [comment]
Thank you for reporting the issue; the bug has been resolved in the code on the 'develop' branch. Use that code, or log out and log back in. The bug occurs when changing the position of the extension.

**Comment by NA0341** [comment]
@0ry0n So if I do not change it myself, would the loading of other extensions at login change it?
I have it to the left where only the small workspace indicator and Overview Button resides.

When that error occurs, it moves to the leftmost position (displacing the Overview Button) and it's display freezes completely.

Btw.: Thank You very much for This incredibly helpful Extension!

For me, keeping a close eye on system resources & conditions is vital when I'm testing stuff that might be buggy (and suddenly flood my storage with copies of copies of files on my computer) or am doing resource-intensive stuff like rendering.
…not to mention very bad memory leaks or runaways.

Also, seeing the amount of free storage grow incremently after deleting BTRFS Snapshots is sooo satisfying 😁🐯

**Comment by gr00vy** [comment]
I have the same problem on Ubuntu 24.04. Unfortunately if I remove this version (24) and install previous working version(22) it just updates to v.24 as soon as I relogin into the desktop session.
So to fix this as soon as you removed version 24 and installed version 22, edit file:
.local/share/gnome-shell/extensions/Resource_Monitor@Ory0n/metadata.json
and change:
"version": 22
to:
"version": 24
This will make Gnome think that you are using the latest version.
This is a temporary fix until they release a really working version (maybe 25?).
Then it will update automatically to it.

**Comment by complanar** [comment]
For me this error occurs when i lock my session and later unlock it again the extension freezes partially, that means the text is not updated any longer. Clicking on it works an brings up the settings or task manager as configured.
